// Generated by https://quicktype.io

export interface Details {
  _id: string;
  name: string;
  items: Item[];
}

export interface Item {
  dateAdded: string;
  _id: string;
  name: string;
  category: string;
}
